engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR2"
  fixme:
      enabled: true
  phpmd:
      enabled: true
      rulesets: "unusedcode,naming,phpmd.xml"
  duplication:
    enabled: true
    config:
      languages:
        php:
ratings:
   paths:
   - "src/**/*"
